build: Pin jupyter client version
The pytest-notebook package depends on a older version of nbconvert
which in turn uses a nbclient package that seems incompatible with the
recent jupyter-client 7.

This leads to errors like:

  TypeError: 'coroutine' object is not subscriptable