upgrade the nlohmann_json from 3.7.3 to 3.10.3 (#758)
* upgrade the nlohmann_json from 3.7.3 to 3.10.4
to avoid variable conflict btw antlr-runtime 4.9.3 and nlohmann_json
due to underspecified EOF without namespace

After switching to the 4.9.3 runtime, encounter this conflict with our json parser. looking at it.
details below:
https://github.com/KatanaGraph/katana-enterprise/pull/2681#issuecomment-996016030

```
/root/.conan/data/nlohmann_json/3.7.3/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/nlohmann/detail/input/binary_reader.hpp:17:
2021-12-16T16:53:42.4746873Z [1m/root/.conan/data/nlohmann_json/3.7.3/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/nlohmann/detail/input/input_adapters.hpp:117:20: [0m[0;1;31merror: [0m[1muse of undeclared identifier 'EOF'; did you mean 'XPathLexer::EOF'?[0m
2021-12-16T16:53:42.4754024Z         if (res == EOF)
2021-12-16T16:53:42.4760480Z [0;1;32m                   ^
2021-12-16T16:53:42.4768646Z [0m[1m/root/.conan/data/antlr4-cppruntime/4.9.3/_/_/package/ed4c50cce248f963b530d644f4c27bd3c33aa7ed/include/antlr4-runtime/Recognizer.h:16:29: [0m[0;1;30mnote: [0m'XPathLexer::EOF' declared here[0m
2021-12-16T16:53:42.4775961Z     static constexpr size_t EOF = std::numeric_limits<size_t>::max();
2021-12-16T16:53:42.4782322Z [0;1;32m                            ^
2021-12-16T16:53:42.4787849Z [0m1 error generated.
2021-12-16T16:53:42.4817761Z make[2]: *** [libquery/test/CMakeFiles/antlr-parser-test.dir/build.make:76: libquery/test/CMakeFiles/antlr-parser-test.dir/antlr-test.cpp.o] Error 1
2021-12-16T16:53:42.4829423Z make[1]: *** [CMakeFiles/Makefile2:8418: libquery/test/CMakeFiles/antlr-parser-test.dir/all] Error 2
```

https://github.com/nlohmann/json/blob/v3.7.3/include/nlohmann/detail/input/input_adapters.hpp#L117

Looks like it is fixed in latest(3.10.4) json parser:
https://github.com/nlohmann/json/blob/v3.10.4/include/nlohmann/detail/input/input_adapters.hpp#L112

* 3.10.4 has known unsolved issue:
https://github.com/nlohmann/json/issues/3090