Resolving snappy conflict (#354)
```
...
snappy/1.1.9: Downloaded recipe revision 0
ERROR: Conflict in mongo-c-driver/1.17.2:
    'mongo-c-driver/1.17.2' requires 'snappy/1.1.9' while 'arrow/2.0.0' requires 'snappy/1.1.8'.
    To fix this conflict you need to override the package 'snappy' in your root package.
...
```