Fallback to installing with conda if mamba fails. (#896)
This is needed because there is some weird case where mamba fails to select the correct packages for download. It shouldn't happen often I think.

This PR fixes failures like this:

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/noarch/charset-normalizer-2.0.11-pyhd8ed1ab_0.conda>

in test_requirements.